### ISSUE TITLE
One reference

### ISSUE THREAD

**Issue by ZhangShiyue** [serenayj/PyrEval#11]
Hi,

I'm trying to use PyrEval for one-reference tasks like CNN/DM summarization. However, it will throw an error. 
When I repeat the reference twice, it works fine. But I don't think the numbers are valid because after repeating 3 or 4 times different numbers are given.  

Could you please help me with this? Thanks!

Shiyue

**Comment by serenayj** [comment]
Hi Shiyue, 

Thanks for your interest in PyrEval. The pyramid evaluation needs at least 3 reference summaries (4-5 ideally), because it evaluates the importance of contents based on their occurrence in distinct references (the "wise crowd" method).  More details could be found in our CoNLL paper. With that said, PyrEval will not be able to evaluate if there is only one reference. Hope it helps!

**Comment by ZhangShiyue** [comment]
I see. Thank you so much!
